stages:
  - build
  - deploy

variables:
  NODE_ENV: dev

build:
  stage: build
  image: node:24-bookworm-slim
  script:
    - npm ci
    - npm run build:develop
    - npm run build:web-components
  artifacts:
    paths:
      - dist/
      - package.json
      - package-lock.json
    expire_in: 1 hour

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - apk add --no-cache git
  script:
    # build docker image from the Dockerfile
    - docker build -t oeb-ui --build-arg NODE_ENV=dev .

    # stop old container if it exists
    - docker rm -f oeb-ui || true

    # run new container on port 3005
    - docker run -p 3005:3005 --restart unless-stopped -d --name oeb-ui oeb-ui
  environment:
    name: dev
  dependencies:
    - build
