services:
  oeb-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oeb-ui
    restart: always
    ports:
      - "3005:3005"   # host:container
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
